#-*- coding: utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Branch.create(name: "Grupo Millenium", webpage: "http://www.grupomillenium.com.mx", email1: "ventas@grupomillenium.com.mx", email2: "ventas@grupomillenium.com.mx", phone1: "N/A", phone2: "N/A", address1: "N/A", address2: "N/A", zip: 32125, city: "Chihuahua", state: "chihuahua", country: "Mexico", description: "N/A")
Role.create(name: "System Administrator", description: "Can manage the complete system.", branch_id: 1, protected: true, super_admin: true, branch_admin: false)
User.create(first_name: 'System', last_name: 'Administrator', username: 'administrator', email: 'aballesteros@emobile.com.mx', password: 'Password1', password_confirmation: 'Password1', confirmed_at: Date.today, branch_id: 1, role_id: 1)
Role.create(name: "Administrador de Sucursal", description: "Puede administrar la sucursal", branch_id: 1, protected: true, super_admin: false, branch_admin: true)
User.create(first_name: 'Usuario', last_name: 'Prueba', username: 'usuario.prueba', email: 'ventas@grupomillenium.com.mx', password: 'Password1', password_confirmation: 'Password1', confirmed_at: Date.today, branch_id: 1, role_id: 2)
Workshop.create(name: "Grupo Millenium", email1: "ventas@grupomillenium.com.mx", email2: "ventas@grupomillenium.com.mx", phone1: "N/A", phone2: "N/A", address1: "N/A", address2: "N/A", zip: 32125, city: "Chihuahua", state: "chihuahua", country: "Mexico", description: "N/A", branch_id: 1, user_id: 2)
Status.create(name: "Recivido", description: "El equipo fue recibido para ser revisado por soporte técnico.", hierarchy: 1, branch_id: 1)
Status.create(name: "Revisión", description: "El equipo se encuentra bajo revisión por soporte técnico.", hierarchy: 2, branch_id: 1)
Status.create(name: "Entregado", description: "El equipo fue entregado a su dueño.", hierarchy: 3, branch_id: 1)
Part.create(name: "Bateria para iphone 4s", description: "Bateria para iphone 4s", serial_number: "10000001", cost: 800, branch_id: 1)
Part.create(name: "Pantalla para Samsung Galaxy 3", description: "Pantalla para Samsung Galaxy 3", serial_number: "10000002", cost: 1600, branch_id: 1)
Part.create(name: "Teclado para Sony Ericson", description: "Teclado para Sony Ericson", serial_number: "10000003", cost: 500, branch_id: 1)
Part.create(name: "Cargador para iPhone", description: "Cargador para iPhone", serial_number: "10000004", cost: 200, branch_id: 1)
Part.create(name: "Audifonos para Samsung Galaxy 3", description: "Audifonos para Samsung Galaxy 3", serial_number: "10000005", cost: 300, branch_id: 1)
ClientNeed.create(name: "Cambiar Bateria", cost: 100, description: "Cambiar Bateria", branch_id: 1)
ClientNeed.create(name: "Cambiar Pantalla", cost: 500, description: "Cambiar Pantalla", branch_id: 1)
ClientNeed.create(name: "Cambiar Teclado", cost: 500, description: "Cambiar Teclado", branch_id: 1)
ClientNeed.create(name: "El equipo no prende", cost: 300, description: "Revisar porque el equipo no prende", branch_id: 1)
ClientNeed.create(name: "El eqipo se apaga solo", cost: 300, description: "Revisar porque el  eqipo se apaga solo", branch_id: 1)

Role.create(name: "Cliente", description: "Puede ver sus ordenes.", branch_id: 1, protected: true, super_admin: false, branch_admin: false, client: true)
#Branch.create(name: "ecom", webpage: "http://www.ecom.com.mx", email1: "aballesteros@emobile.com.mx", email2: "aballesteros@emobile.com.mx", phone1: "18009345674", phone2: "18009345674", address1: "N/A", address2: "N/A", zip: 32125, city: "Chihuahua", state: "chihuahua", country: "Mexico", description: "N/A")
#Role.create(name: "Branch Administrator", description: "Can manage branch.", branch_id: 1, protected: true, super_admin: false, branch_admin: true)
#User.create(first_name: 'Branch', last_name: 'Administrator', username: 'administrator1', email: 'aballesteros@emobile.com.mx', password: 'Password1', password_confirmation: 'Password1', confirmed_at: Date.today, branch_id: 2, role_id: 2)
#Workshop.create(name: "ecom", email1: "emobile@emobile.com.mx", email2: "support@emobile.com.mx", phone1: "18009345674", phone2: "18009345674", address1: "N/A", address2: "N/A", zip: 32125, city: "Chihuahua", state: "chihuahua", country: "Mexico", description: "N/A", branch_id: 2, user_id: 2)
#Status.create(name: "Recivido", description: "Recivido", hierarchy: 1, branch_id: 2)
#Status.create(name: "En revicion", description: "Recivido", hierarchy: 2, branch_id: 2)
#Status.create(name: "Entregado", description: "Recivido", hierarchy: 3, branch_id: 2)
#Part.create(name: "Memoria Ram 4GB", description: "Memoria Ram 4GB", serial_number: "10000001", cost: 800, branch_id: 2)
#Part.create(name: "Memoria Ram 8GB", description: "Memoria Ram 8GB", serial_number: "10000002", cost: 1600, branch_id: 2)
#Part.create(name: "Disco Duro SATA 1TB", description: "Disco Duro SATA 1TB", serial_number: "10000003", cost: 500, branch_id: 2)
#Part.create(name: "Disco Duro SATA 2TB", description: "Disco Duro SATA 2TB", serial_number: "10000004", cost: 1000, branch_id: 2)
#Part.create(name: "CROM 42x", description: "CROM 42x", serial_number: "10000005", cost: 300, branch_id: 2)
#Part.create(name: "Teclado MacBook Pro 13", description: "Teclado MacBook Pro 13", serial_number: "10000006", cost: 2000, branch_id: 2)
#
#Branch.create(name: "xoftwareit", webpage: "http://www.xoftwareit.com.mx", email1: "apple_development@emobile.com.mx", email2: "support@emobile.com.mx", phone1: "18009345674", phone2: "18009345674", address1: "N/A", address2: "N/A", zip: 32125, city: "Chihuahua", state: "chihuahua", country: "Mexico", description: "N/A")
#Role.create(name: "Test Administrator", description: "Can test system.", branch_id: 1, protected: true, super_admin: false, branch_admin: false)
#User.create(first_name: 'Test', last_name: 'Administrator', username: 'administrator2', email: 'apple_development@emobile.com.mx', password: 'Password1', password_confirmation: 'Password1', confirmed_at: Date.today, branch_id: 3, role_id: 3)
#Workshop.create(name: "xoftwareit", email1: "emobile@emobile.com.mx", email2: "support@emobile.com.mx", phone1: "18009345674", phone2: "18009345674", address1: "N/A", address2: "N/A", zip: 32125, city: "Chihuahua", state: "chihuahua", country: "Mexico", description: "N/A", branch_id: 3, user_id: 3)
#Status.create(name: "Recivido", description: "Recivido", hierarchy: 1, branch_id: 3)
#Status.create(name: "En revicion", description: "Recivido", hierarchy: 2, branch_id: 3)
#Status.create(name: "Entregado", description: "Recivido", hierarchy: 3, branch_id: 3)
#Part.create(name: "Memoria Ram 4GB", description: "Memoria Ram 4GB", serial_number: "10000001", cost: 800, branch_id: 3)
#Part.create(name: "Memoria Ram 8GB", description: "Memoria Ram 8GB", serial_number: "10000002", cost: 1600, branch_id: 3)
#Part.create(name: "Disco Duro SATA 1TB", description: "Disco Duro SATA 1TB", serial_number: "10000003", cost: 500, branch_id: 3)
#Part.create(name: "Disco Duro SATA 2TB", description: "Disco Duro SATA 2TB", serial_number: "10000004", cost: 1000, branch_id: 3)
#Part.create(name: "CROM 42x", description: "CROM 42x", serial_number: "10000005", cost: 300, branch_id: 3)
#Part.create(name: "Teclado MacBook Pro 13", description: "Teclado MacBook Pro 13", serial_number: "10000006", cost: 2000, branch_id: 3)
#
#Branch.create(name: "Compu Place", webpage: "http://www.compuplace.com.mx", email1: "aflores@compuplace.com.mx", email2: "support@emobile.com.mx", phone1: "(614) 415-6849", phone2: "(614) 437-1961", address1: "Calle 24, no. 2306", address2: "Col. Mirador", zip: 31205, city: "Chihuahua", state: "chihuahua", country: "Mexico", description: "Calidad y Servicio de Computacíon")
#Role.create(name: "Administrador", description: "Puede administrar el sistema", branch_id: 4, protected: true, super_admin: false, branch_admin: true)
#User.create(first_name: 'Adriana', last_name: 'Flores Alvarez', username: 'adrianaflores', email: 'aflores@compuplace.com.mx', password: 'Password1', password_confirmation: 'Password1', confirmed_at: Date.today, branch_id: 4, role_id: 2)
#Workshop.create(name: "Compu Place", email1: "aflores@compuplace.com.mx", email2: "aflores@compuplace.com.mx", phone1: "(614) 415-6849", phone2: "(614) 437-1961", address1: "Calle 24, no. 2306", address2: "Col. Mirador", zip: 31205, city: "Chihuahua", state: "chihuahua", country: "Mexico", description: "Calidad y Servicio de Computacíon", branch_id: 4, user_id: 4)
#Status.create(name: "Recivido", description: "Recivido", hierarchy: 1, branch_id: 4)
#Status.create(name: "En revicion", description: "Recivido", hierarchy: 2, branch_id: 4)
#Status.create(name: "Entregado", description: "Recivido", hierarchy: 3, branch_id: 4)
#Part.create(name: "Memoria Ram 4GB", description: "Memoria Ram 4GB", serial_number: "10000001", cost: 800, branch_id: 4)
#Part.create(name: "Memoria Ram 8GB", description: "Memoria Ram 8GB", serial_number: "10000002", cost: 1600, branch_id: 4)
#Part.create(name: "Disco Duro SATA 1TB", description: "Disco Duro SATA 1TB", serial_number: "10000003", cost: 500, branch_id: 4)
#Part.create(name: "Disco Duro SATA 2TB", description: "Disco Duro SATA 2TB", serial_number: "10000004", cost: 1000, branch_id: 4)
#Part.create(name: "CROM 42x", description: "CROM 42x", serial_number: "10000005", cost: 300, branch_id: 4)
#Part.create(name: "Teclado MacBook Pro 13", description: "Teclado MacBook Pro 13", serial_number: "10000006", cost: 2000, branch_id: 4)
#ClientNeed.create(name: "Revisión general", description: "Revisión general del dispositivo.", cost: 50, branch_id: 4)
#ClientNeed.create(name: "Cambiar memoria RAM", description: "Cambiar memoria RAM.", cost: 100, branch_id: 4)
#ClientNeed.create(name: "Cambiar disco duro", description: "Cambiar disco duro.", cost: 150, branch_id: 4)
#ClientNeed.create(name: "Reparar teclado", description: "Reparar teclado.", cost: 200, branch_id: 4)
#ClientNeed.create(name: "Reparar monitor", description: "Reparar monitor.", cost: 250, branch_id: 4)
#ClientNeed.create(name: "Cambiar procesador", description: "Cambiar procesador.", cost: 300, branch_id: 4)
#ClientNeed.create(name: "Formatear computadora", description: "Formatear computadora.", cost: 350, branch_id: 4)
#ClientNeed.create(name: "Cambiar sistema operativo", description: "Cambiar sistema operativo.", cost: 400, branch_id: 4)
#ClientNeed.create(name: "Instalar software", description: "Instalar software.", cost: 450, branch_id: 4)
#ClientNeed.create(name: "Reparar sistema de ventilacion", description: "Reparar sistema de ventilacion.", cost: 500, branch_id: 4)

Client.create(first_name: 'Javier Alejandro', last_name: 'Ballesteros Fierro', username: 'cliente1', email: 'cliente1@hotmail.com', password: 'Password1', password_confirmation: 'Password1', confirmed_at: Date.today, phone1: "(614) 123-4567", phone2: "(614) 123-4567", address1: "Calle No. 1234", address2: "Fracc. Las Huertas", city: "Chihuahua", state: "Chihuahua", zip: 31212, country: "Mexico", active: true, branch_id: 1, role_id: 3)
Bill.create(name: "Javier Alejandro Ballesteros Fierro", rfc: "rfc1234567890", client_id: 1, fax: "(614) 123-4567", phone1: "(614) 123-4567", phone2: "(614) 123-4567", address1: "Calle No. 1234", address2: "Fracc. Las Huertas", city: "Chihuahua", state: "Chihuahua", zip: 31212, country: "Mexico")
Cellphone.create(model: "iPhone 5s", brand: "Apple", color: "Black", ope_system: "iOS 7", imei: "12345678901234", client_id: 1, branch_id: 1)
#Computer.create(model: "Qosmio 545", brand: "Toshiba", color: "Red", ope_system: "Windows 7", serial_number: "efw2342342", computer_type: "Laptop", hard_drive: "500 GB", memory: "1 TB", proccessor: "i7 2.3 Hz", charger: "Yes", usb: "No", monitor: "No", keyboard: "No", mouse: "Yes", client_id: 1, branch_id: 1)

Client.create(first_name: 'Manuel', last_name: 'Aguirre Lopez', username: 'cliente2', email: 'cliente2@hotmail.com', password: 'Password1', password_confirmation: 'Password1', confirmed_at: Date.today, phone1: "(714) 502-8596", phone2: "(714) 126-2334", address1: "Calle No. 1235", address2: "Fracc. Olmos", city: "Queretaro", state: "Queretaro", zip: 31100, country: "Mexico", active: true, branch_id: 1, role_id: 3)
Bill.create(name: "Manuel Aguirre Lopez", rfc: "agm3502124565", client_id: 2, fax: "(714) 345-6578", phone1: "(714) 564-9857 ", phone2: "(714) 657-9845", address1: "Calle No. 1235", address2: "Fracc. Las Olmos", city: "Queretaro", state: "Queretaro", zip: 31100, country: "Mexico")
Cellphone.create(model: "Nokia Lumia", brand: "Nokia", color: "Black", ope_system: "windows phone", imei: "123456789012346", client_id: 2, branch_id: 1)
#Computer.create(model: "Macbook", brand: "Apple", color: "Black", ope_system: "Lion", serial_number: "efwr4t7343", computer_type: "Laptop", hard_drive: "160 GB", memory: "1 TB", proccessor: "i5 2.3 Hz", charger: "Yes", usb: "Yes", monitor: "No", keyboard: "No", mouse: "No", client_id: 2, branch_id: 2)

Client.create(first_name: 'Osiel', last_name: 'Bonilla Quezada', username: 'cliente3', email: 'cliente3@hotmail.com', password: 'Password1', password_confirmation: 'Password1', confirmed_at: Date.today, phone1: "(614) 129-7856", phone2: "(614) 295-586", address1: "Calle No. 7586", address2: "Fracc. Infonavit", city: "Chihuahua", state: "Chihuahua", zip: 31485, country: "Mexico", active: true, branch_id: 1, role_id: 3)
Bill.create(name: "Osiel Bonilla Quezada", rfc: "obq1234585462", client_id: 3, fax: "(614) 265-856", phone1: "(614) 785-695", phone2: "(614) 256-695", address1: "Calle No.7586 ", address2: "Fracc. Las Huertas", city: "Chihuahua", state: "Chihuahua", zip: 31485, country: "Mexico")
Cellphone.create(model: "Razr D3", brand: "Motorola", color: "White", ope_system: "Android 2.1", imei: "123456778965456", client_id: 3, branch_id: 1)
#Computer.create(model: "Pro 3515", brand: "HP", color: "Blue", ope_system: "Windows 7", serial_number: "o8er342965", computer_type: "Desktop", hard_drive: "1 TB", memory: "4 GB", proccessor: "i3 1.4 Hz", charger: "Yes", usb: "Yes", monitor: "Yes", keyboard: "Yes", mouse: "Yes", client_id: 3, branch_id: 3)

Client.create(first_name: 'Jhon', last_name: 'Smit', username: 'cliente4', email: 'cliente4@hotmail.com', password: 'Password1', password_confirmation: 'Password1', confirmed_at: Date.today, phone1: "(758) 856-9865", phone2: "(758) 123-4567", address1: "Street No. 9865", address2: "Alcoas", city: "Amityville", state: "New York", zip: 96532, country: "USA", active: true, branch_id: 1, role_id: 3)
Bill.create(name: "Jhon Smit", rfc: "jsa8546325418", client_id: 4, fax: "(758) 965-4567", phone1: "(758) 865-548", phone2: "(758) 695-9865", address1: "Street No. 9865", address2: "Alcoas", city: "Amitville", state: "New York", zip: 96532, country: "USA")
Cellphone.create(model: "Ilium", brand: "Lanix", color: "Pink", ope_system: "Android 4.0", imei: "963258741253601", client_id: 4, branch_id: 1)
#Computer.create(model: "Vostro 470", brand: "Dell", color: "Red", ope_system: "Windows xp", serial_number: "wer8965342", computer_type: "Desktop", hard_drive: "320 GB", memory: "2 GB", proccessor: "i2 2.0 Hz", charger: "Yes", usb: "Yes", monitor: "Yes", keyboard: "Yes", mouse: "Yes", client_id: 4, branch_id: 1)

Client.create(first_name: 'Laurie', last_name: 'Kirschner', username: 'cliente5', email: 'cliente5@hotmail.com', password: 'Password1', password_confirmation: 'Password1', confirmed_at: Date.today, phone1: "(854) 789-6532", phone2: "(854) 986-9865", address1: "Street No. 8965 ", address2: "Ina", city: "Beverly Hills", state: "California", zip:89657, country: "USA", active: true, branch_id: 1, role_id: 3)
Bill.create(name: "Laurie Kirschner", rfc: "rfc1234567345", client_id: 5, fax: "(614) 345-4567", phone1: "(614) 345-4567", phone2: "(854) 986-6536", address1: "Street No. 8965", address2: "Ina", city: "Beverly Hills", state: "California", zip: 89657, country: "USA")
Cellphone.create(model: "iPhone 4s", brand: "Apple", color: "Black", ope_system: "iOS 7", imei: "123456965328547", client_id: 5, branch_id: 1)
#Computer.create(model: "Inspiron 14", brand: "Dell", color: "Green", ope_system: "Windows 8", serial_number: "efw879wt68", computer_type: "Notebook", hard_drive: "300 GB", memory: "4 GB", proccessor: "i3 1.2 Hz", charger: "Yes", usb: "No", monitor: "No", keyboard: "No", mouse: "No", client_id: 5, branch_id: 2)

Client.create(first_name: 'Alberto', last_name: 'Montes Velazquez', username: 'cliente6', email: 'cliente6@hotmail.com', password: 'Password1', password_confirmation: 'Password1', confirmed_at: Date.today, phone1: "(652) 103-8542", phone2: "(652) 103-8542", address1: "Calle No. 987", address2: "Col. Centro", city: "Guadalajara", state: "Jalisco", zip: 98653, country: "Mexico", active: true, branch_id: 1, role_id: 3)
Bill.create(name: "Alberto Montes Velazquez", rfc: "mov1965081298", client_id: 6, fax: "(652) 103-8542", phone1: "(652) 103-8542", phone2: "(652) 103-8542", address1: "Calle No. 987 ", address2: "Col. Centro", city: "Guadalajara", state: "Jalisco", zip: 98653, country: "Mexico")
Cellphone.create(model: "Asha 205", brand: "Nokia", color: "White", ope_system: "windows phone", imei: "963258874569852", client_id: 6, branch_id: 1)
#Computer.create(model: "Aspire AZ3771", brand: "Acer", color: "Black", ope_system: "Windows 8", serial_number: "efw96387542", computer_type: "Desktop", hard_drive: "1 TB", memory: "8 GB", proccessor: "i3 2.3 Hz", charger: "Yes", usb: "Yes", monitor: "Yes", keyboard: "Yes", mouse: "Yes", client_id: 6, branch_id: 3)

